# The name of the workflow
name: Build and Deploy

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Main component of workflow, consists multiple steps
jobs:
  # This workflow contains a single job called "build"
  build:
    # The destination machine, contain a sequence of tasks (steps)
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Select an action as part of step. Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Name of step
      - name: Deploy to Github Pages 
        # Runs a single command using the runners shell
        run: echo Hello, world!

      # Name of step
      - name: Run a multi-line script
        # Runs a set of commands using the runners shell
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
